namespace R25_Database_Editor
{
    /// <summary>
    /// String Array Class.
    /// </summary>
    /// <remarks>
    ///   R25 Database Editor. Written by Wouldubeinta
    ///   Copyright (C) 2025 Wouldy Mods.
    ///   
    ///   This program is free software; you can redistribute it and/or
    ///   modify it under the terms of the GNU General Public License
    ///   as published by the Free Software Foundation; either version 3
    ///   of the License, or (at your option) any later version.
    ///   
    ///   This program is distributed in the hope that it will be useful,
    ///   but WITHOUT ANY WARRANTY; without even the implied warranty of
    ///   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    ///   GNU General Public License for more details.
    ///   
    ///   You should have received a copy of the GNU General Public License
    ///   along with this program; if not, write to the Free Software
    ///   Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
    /// 
    ///   The author may be contacted at:
    ///   Discord: Wouldubeinta
    /// </remarks>
    /// <history>
    /// [Wouldubeinta]	   09/11/2025	Created
    /// </history>
    public class StringArrays
    {
        public static readonly string[] CountryOfBirth =
        {
            "Afghanistan",
            "Algeria",
            "American Samoa",
            "Andorra",
            "Argentina",
            "Armenia",
            "Aruba",
            "Australia",
            "Austria",
            "Bahamas",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Bermuda",
            "Bolivia",
            "Bonaire",
            "Bosnia And Herzegovina",
            "Botswana",
            "Brazil",
            "British Virgin Islands",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cameroon",
            "Canada",
            "Central African Republic",
            "Chile",
            "China",
            "Chinese Taipei",
            "Colombia",
            "Cote Divoire",
            "Croatia",
            "Curacao",
            "Cyprus",
            "Czechia",
            "Denmark",
            "DRCongo",
            "Egypt",
            "El Salvador",
            "England",
            "Estonia",
            "Eswatini",
            "Fiji",
            "Finland",
            "France",
            "Georgia",
            "Germany",
            "Grenada",
            "Guam",
            "Guatemala",
            "Guyana",
            "Honduras",
            "Hong Kong",
            "Iceland",
            "India",
            "Indonesia",
            "Iraq",
            "Ireland",
            "Isle Of Man",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jersey",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macau",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Mali",
            "Malta",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Moldova",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Mozambique",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Niue",
            "Norway",
            "Oman",
            "Pakistan",
            "Palestine",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Puerto Rico",
            "Qatar",
            "Romania",
            "Russia",
            "Rwanda",
            "Saint Vincent And The Grenadines",
            "Samoa",
            "San Marino",
            "Saudi Arabia",
            "Scotland",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovenia",
            "Solomon Islands",
            "South Africa",
            "South Korea",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "St Barthelemy",
            "Sudan",
            "Sweden",
            "Switzerland",
            "Tahiti",
            "Tanzania",
            "Thailand",
            "Tonga",
            "Trinidad Tobago",
            "Turkey",
            "TurksCaicos",
            "Tuvalu",
            "Uganda",
            "United Arab Emirates",
            "United States",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Venezuela",
            "Wales",
            "Zambia",
            "Zimbabwe",
            "Other",
            "Haiti",
            "Guinea"
        };

        public static readonly string[] Affiliations =
        {
            "Afghanistan",
            "Algeria",
            "American Samoa",
            "Andorra",
            "Argentina",
            "Armenia",
            "Aruba",
            "Australia",
            "Austria",
            "Bahamas",
            "Bangladesh",
            "Barbados",
            "Belarus",
            "Belgium",
            "Bermuda",
            "Bolivia",
            "Bonaire",
            "Bosnia And Herzegovina",
            "Botswana",
            "Brazil",
            "British Virgin Islands",
            "Brunei",
            "Bulgaria",
            "Burkina Faso",
            "Burundi",
            "Cameroon",
            "Canada",
            "Central African Republic",
            "Chile",
            "China",
            "Chinese Taipei",
            "Colombia",
            "Cote Divoire",
            "Croatia",
            "Curacao",
            "Cyprus",
            "Czechia",
            "Denmark",
            "DRCongo",
            "Egypt",
            "El Salvador",
            "England",
            "Estonia",
            "Eswatini",
            "Fiji",
            "Finland",
            "France",
            "Georgia",
            "Germany",
            "Grenada",
            "Guam",
            "Guatemala",
            "Guyana",
            "Honduras",
            "Hong Kong",
            "Iceland",
            "India",
            "Indonesia",
            "Iraq",
            "Ireland",
            "Isle Of Man",
            "Israel",
            "Italy",
            "Jamaica",
            "Japan",
            "Jersey",
            "Kazakhstan",
            "Kenya",
            "Kiribati",
            "Kyrgyzstan",
            "Laos",
            "Latvia",
            "Lebanon",
            "Lesotho",
            "Libya",
            "Liechtenstein",
            "Lithuania",
            "Luxembourg",
            "Macau",
            "Madagascar",
            "Malawi",
            "Malaysia",
            "Mali",
            "Malta",
            "Mauritania",
            "Mauritius",
            "Mexico",
            "Moldova",
            "Mongolia",
            "Montenegro",
            "Morocco",
            "Mozambique",
            "Namibia",
            "Nauru",
            "Nepal",
            "Netherlands",
            "New Zealand",
            "Nicaragua",
            "Niger",
            "Nigeria",
            "Niue",
            "Norway",
            "Oman",
            "Pakistan",
            "Palestine",
            "Panama",
            "Papua New Guinea",
            "Paraguay",
            "Peru",
            "Philippines",
            "Poland",
            "Portugal",
            "Puerto Rico",
            "Qatar",
            "Romania",
            "Russia",
            "Rwanda",
            "Saint Vincent And The Grenadines",
            "Samoa",
            "San Marino",
            "Saudi Arabia",
            "Scotland",
            "Senegal",
            "Serbia",
            "Seychelles",
            "Sierra Leone",
            "Singapore",
            "Slovenia",
            "Solomon Islands",
            "South Africa",
            "South Korea",
            "South Sudan",
            "Spain",
            "Sri Lanka",
            "St Barthelemy",
            "Sudan",
            "Sweden",
            "Switzerland",
            "Tahiti",
            "Tanzania",
            "Thailand",
            "Tonga",
            "Trinidad Tobago",
            "Turkey",
            "TurksCaicos",
            "Tuvalu",
            "Uganda",
            "United Arab Emirates",
            "United States",
            "Uruguay",
            "Uzbekistan",
            "Vanuatu",
            "Venezuela",
            "Wales",
            "Zambia",
            "Zimbabwe",
            "Other",
            "Haiti",
            "Guinea",
            "State Of Origin - Unaligned",
            "State Of Origin - Queensland",
            "State Of Origin - NSW",
            "City Vs Country - Unaligned",
            "City Vs Country - City",
            "City Vs Country - Country",
            "AllStars - Unaligned",
            "AllStars - Maori",
            "AllStars - Indigenous",
            "None"
        };

        public static readonly string[] Stadiums =
        {
            "Stade de France",
            "Stade Pierre Mauroy",
            "Stade de la Beaujoire",
            "Stadium de Toulouse",
            "Groupama Stadium",
            "Atlantic Stadium Bordeaux Metropole",
            "Stade Geoffroy-Guichard",
            "Allianz Riviera",
            "Orange Vélodrome",
            "Eden Park",
            "Suncorp Stadium",
            "Aviva Stadium",
            "Millennium Stadium",
            "Emirates Airline Park",
            "Stadio Olimpico",
            "Murrayfield Stadium",
            "José Amalfitani Stadium",
            "Chichibunomiya Rugby Stadium",
            "Estadio Charrúa",
            "Hage Geingob Stadium",
            "Teufaiva Sport Stadium",
            "Arcul de Triumf Stadium",
            "Estádio Nacional",
            "Mikheil Meskhi Stadium",
            "Apia Park",
            "HFC Bank Stadium",
            "Estadio Germán Becker",
            "Estadio Nacional Complutense",
            "Stadio Comunale di Monigo",
            "Loftus Versfeld Stadium",
            "Cardiff Arms Park",
            "Dexcom Stadium",
            "Rodney Parade",
            "Hive Stadium",
            "Scotstoun Stadium",
            "Thomond Park",
            "Swansea.com Stadium",
            "Parc y Scarlets",
            "Hollywoodbets Kings Park Stadium",
            "DHL Stadium",
            "Ravenhill Stadium",
            "Stadio Sergio Lanfranchi",
            "Stade Jean-Dauger",
            "Stade de la Rabine",
            "Stade Chaban-Delmas",
            "Stade Pierre-Fabre",
            "Stade Marcel-Michelin",
            "Stade Marcel-Deflandre",
            "Matmut Stadium de Gerland",
            "Septeo Stadium",
            "Estadio du Hameau",
            "Stade Aimé Giral",
            "Stade Jean-Bouin (Paris)",
            "Ile de France",
            "Stade Mayol",
            "Stadium de Toulouse",
            "Stade Amédée-Domenech",
            "Bath Stadium",
            "Ashton Gate Stadium",
            "Sandy Park (Exeter, England)",
            "Kingsholm Stadium (Gloucester)",
            "Allianz Stadium (Twickenham)",
            "Mattioli Woods Welford Road Stadium",
            "Kingston Park (Newcastle, England)",
            "Franklin's Gardens (Northampton, England)",
            "CorpAcq Stadium",
            "StoneX Stadium",
            "SaberCats Stadium (Houston)",
            "Snapdragon Stadium (San Diego)",
            "Twickenham Stadium",
            "Soldier Field (Chicago)",
            "Choctaw Stadium (Arlington)",
            "Veterans Memorial Stadium (Quincy, Massachusetts)",
            "Gold Mine on Airline  (New Orleans)",
            "Starfire Sports (Seattle)",
            "America First Field (Salt Lake City)",
            "AutoNation Sports Field (Florida)",
            "Maureen Hendrick's Field (Maryland)",
            "Stade Municipal (Switzerland)",
            "Allianz Stadium (Sydney)",
            "FMG Stadium Waikato (Hamilton, NZ)",
            "HBF Park (Perth)",
            "Forsyth Barr Stadium (Dunedin, NZ)",
            "Sky Stadium (Wellington, NZ)",
            "Rugby League Park (Christchurch, NZ)",
            "Canberra Stadium (AUS)",
            "Training Ground",
            "Virgin Media Park (Cork, Ireland)",
            "Stadio Olimpico (Rome)",
            "Principality Stadium (Wales)",
            "Stadio Comunale Di Monigo (Italy)",
            "Loftus Versfeld Stadium (Pretoria, South Africa)",
            "Emirates Airline Park (Johannesburg, South Africa)",
            "Stadio Sergio Lanfranchi (Parma, Italy)",
            "Kings Park Stadium (Durban, South Africa)",
            "Cape Town Stadium",
            "Thomond Park (Limerick, Ireland)",
            "Copthall Stadium",
            "American Express Stadium (Brighton)",
            "York Stadium"
        };

        public static readonly string[] LogosPNG =
        {
            "ban_bangladesh_amatuers.pc.png",
            "ban_chhatak.pc.png",
            "ban_dinajpur.pc.png",
            "ban_flame_boys.pc.png",
            "ban_jbrc.pc.png",
            "ban_kurigram.pc.png",
            "ban_magura.pc.png",
            "ban_narail.pc.png",
            "ban_national.pc.png",
            "ban_ogrojatra.pc.png",
            "ban_satkhira.pc.png",
            "ban_sha_academy.pc.png",
            "bel_asab.pc.png",
            "bel_bofferdring.pc.png",
            "bel_boitsfort.pc.png",
            "bel_coq_mosan.pc.png",
            "bel_dendermonde.pc.png",
            "bel_frameries.pc.png",
            "bel_la_hulpe.pc.png",
            "bel_leuven.pc.png",
            "bel_liege.pc.png",
            "bel_rc9_huesden.pc.png",
            "bel_roc.pc.png",
            "bel_royal_kituro.pc.png",
            "bel_soignies.pc.png",
            "bra_charrua.pc.png",
            "bra_curitibia.pc.png",
            "bra_desterro.pc.png",
            "bra_farrapos.pc.png",
            "bra_jacarei.pc.png",
            "bra_jaoca.pc.png",
            "bra_niteroi.pc.png",
            "bra_pasteur.pc.png",
            "bra_piracicaba.pc.png",
            "bra_poli.pc.png",
            "bra_sanjose.pc.png",
            "bra_saopaulo.pc.png",
            "bra_spac.pc.png",
            "bra_tornados.pc.png",
            "bra_verrmelho.pc.png",
            "club_brazil_cobras.pc.png",
            "club_brussel_devils.pc.png",
            "club_cafeteros.pc.png",
            "club_lusitanos.pc.png",
            "club_namibia_welwitschias.pc.png",
            "club_netherlands_delta.pc.png",
            "club_selknam.pc.png",
            "club_telaviv.pc.png",
            "club_zimbawe_goshawks.pc.png",
            "custom.pc.png",
            "cus_01.pc.png",
            "cus_02.pc.png",
            "cus_03.pc.png",
            "cus_04.pc.png",
            "cus_05.pc.png",
            "cus_06.pc.png",
            "cus_07.pc.png",
            "cus_08.pc.png",
            "cus_09.pc.png",
            "cus_10.pc.png",
            "cus_11.pc.png",
            "cus_12.pc.png",
            "cus_13.pc.png",
            "cus_14.pc.png",
            "cus_15.pc.png",
            "cus_16.pc.png",
            "cus_17.pc.png",
            "cus_18.pc.png",
            "cus_19.pc.png",
            "cus_20.pc.png",
            "cus_21.pc.png",
            "cus_22.pc.png",
            "cus_23.pc.png",
            "cus_24.pc.png",
            "cus_25.pc.png",
            "cus_26.pc.png",
            "cus_27.pc.png",
            "cus_28.pc.png",
            "cus_29.pc.png",
            "cus_30.pc.png",
            "cus_31.pc.png",
            "cus_32.pc.png",
            "cus_33.pc.png",
            "cus_34.pc.png",
            "cus_35.pc.png",
            "cus_36.pc.png",
            "cus_37.pc.png",
            "cus_38.pc.png",
            "cus_39.pc.png",
            "cus_40.pc.png",
            "cus_42.pc.png",
            "cus_43.pc.png",
            "cus_44.pc.png",
            "cus_47.pc.png",
            "cus_48.pc.png",
            "cus_49.pc.png",
            "cus_51.pc.png",
            "cus_52.pc.png",
            "cus_53.pc.png",
            "cus_54.pc.png",
            "cus_55.pc.png",
            "cus_56.pc.png",
            "cus_57.pc.png",
            "cus_58.pc.png",
            "cus_59.pc.png",
            "cus_60.pc.png",
            "cus_61.pc.png",
            "cus_62.pc.png",
            "cus_63.pc.png",
            "cus_64.pc.png",
            "cus_65.pc.png",
            "cus_66.pc.png",
            "cus_67.pc.png",
            "cus_68.pc.png",
            "cus_69.pc.png",
            "cus_70.pc.png",
            "cus_71.pc.png",
            "cus_72.pc.png",
            "cus_73.pc.png",
            "cus_74.pc.png",
            "cus_75.pc.png",
            "cus_76.pc.png",
            "cus_78.pc.png",
            "cus_79.pc.png",
            "cus_80.pc.png",
            "epr_bath.pc.png",
            "epr_bristol.pc.png",
            "epr_exeter.pc.png",
            "epr_gloucester.pc.png",
            "epr_harlequins.pc.png",
            "epr_leicester.pc.png",
            "epr_newcastle.pc.png",
            "epr_northampton.pc.png",
            "epr_sale.pc.png",
            "epr_saracens.pc.png",
            "int_algeria.pc.png",
            "int_american_samoa.pc.png",
            "int_andorra.pc.png",
            "int_argentina.pc.png",
            "int_armenia.pc.png",
            "int_aruba.pc.png",
            "int_australia.pc.png",
            "int_australia_w.pc.png",
            "int_austria.pc.png",
            "int_bahamas.pc.png",
            "int_bangladesh.pc.png",
            "int_barbados.pc.png",
            "int_belarus.pc.png",
            "int_belgium.pc.png",
            "int_belgium_team.pc.png",
            "int_bermuda.pc.png",
            "int_bolivia.pc.png",
            "int_bonaire.pc.png",
            "int_bosnia_herzegovina.pc.png",
            "int_botswana.pc.png",
            "int_brazil.pc.png",
            "int_brazil_2.pc.png",
            "int_brazil_2_w.pc.png",
            "int_brazil_cobras.pc.png",
            "int_brazil_super12.pc.png",
            "int_brunei.pc.png",
            "int_brussels_devisl.pc.png",
            "int_bulgaria.pc.png",
            "int_burkino_faso.pc.png",
            "int_burundi.pc.png",
            "int_bvi.pc.png",
            "int_cameroon.pc.png",
            "int_canada.pc.png",
            "int_central_african_republic.pc.png",
            "int_chile.pc.png",
            "int_chile_condores.pc.png",
            "int_chile_selknam.pc.png",
            "int_china.pc.png",
            "int_chinese_taipai.pc.png",
            "int_columbia.pc.png",
            "int_columbia_2.pc.png",
            "int_croatia.pc.png",
            "int_curacao.pc.png",
            "int_cyprus.pc.png",
            "int_czechia.pc.png",
            "int_denmark.pc.png",
            "int_dr_congo.pc.png",
            "int_egypt.pc.png",
            "int_el_salvador.pc.png",
            "int_england.pc.png",
            "int_estonia.pc.png",
            "int_eswatini.pc.png",
            "int_eswatini_2.pc.png",
            "int_fiji.pc.png",
            "int_finland.pc.png",
            "int_france.pc.png",
            "int_georgia.pc.png",
            "int_germany.pc.png",
            "int_germany_2.pc.png",
            "int_grenada.pc.png",
            "int_guam.pc.png",
            "int_guatemala.pc.png",
            "int_guyana.pc.png",
            "int_honduras.pc.png",
            "int_hongkong.pc.png",
            "int_iceland.pc.png",
            "int_india.pc.png",
            "int_indonesia.pc.png",
            "int_iraq.pc.png",
            "int_ireland.pc.png",
            "int_isleofman.pc.png",
            "int_israel.pc.png",
            "int_israel_telaviv.pc.png",
            "int_italy.pc.png",
            "int_ivory_coast.pc.png",
            "int_ivory_coast_2.pc.png",
            "int_jamaica.pc.png",
            "int_japan.pc.png",
            "int_kazakhstan.pc.png",
            "int_kenya.pc.png",
            "int_kiribati.pc.png",
            "int_korea.pc.png",
            "int_kyrgyzstan.pc.png",
            "int_laos.pc.png",
            "int_latvia.pc.png",
            "int_lebanon.pc.png",
            "int_lebanon_phoenix.pc.png",
            "int_lesotho.pc.png",
            "int_libya.pc.png",
            "int_liechtenstein.pc.png",
            "int_lithuania.pc.png",
            "int_luxembourg.pc.png",
            "int_macau.pc.png",
            "int_madagascar.pc.png",
            "int_malawi.pc.png",
            "int_malawi_2.pc.png",
            "int_malaysia.pc.png",
            "int_mali.pc.png",
            "int_mali_team.pc.png",
            "int_malta.pc.png",
            "int_mauritania.pc.png",
            "int_mauritius.pc.png",
            "int_mexico.pc.png",
            "int_moldova.pc.png",
            "int_mongolia.pc.png",
            "int_montenegro.pc.png",
            "int_montenegro_2.pc.png",
            "int_morocco.pc.png",
            "int_mozambique.pc.png",
            "int_namibia.pc.png",
            "int_namibia_welwitschias.pc.png",
            "int_nauru.pc.png",
            "int_nepal.pc.png",
            "int_netherlands.pc.png",
            "int_netherlands_delta.pc.png",
            "int_new_zealand.pc.png",
            "int_nicaragua.pc.png",
            "int_niger.pc.png",
            "int_nigeria.pc.png",
            "int_niue_island.pc.png",
            "int_norway.pc.png",
            "int_nz_black_ferns.pc.png",
            "int_oman.pc.png",
            "int_pakistan.pc.png",
            "int_palestine.pc.png",
            "int_panama.pc.png",
            "int_paraguay.pc.png",
            "int_peru.pc.png",
            "int_philippines.pc.png",
            "int_png.pc.png",
            "int_poland.pc.png",
            "int_portugal.pc.png",
            "int_portugal_national.pc.png",
            "int_puerto_rico.pc.png",
            "int_qatar.pc.png",
            "int_romania.pc.png",
            "int_russia.pc.png",
            "int_rwanda.pc.png",
            "int_samoa_men.pc.png",
            "int_samoa_under15s.pc.png",
            "int_samoa_women.pc.png",
            "int_sanmarino.pc.png",
            "int_saudi_arabia.pc.png",
            "int_scotland.pc.png",
            "int_senegal.pc.png",
            "int_serbia.pc.png",
            "int_seychelles.pc.png",
            "int_sierra_leone.pc.png",
            "int_singapore.pc.png",
            "int_slovenia.pc.png",
            "int_solomon_islands.pc.png",
            "int_southsudan.pc.png",
            "int_south_africa.pc.png",
            "int_spain.pc.png",
            "int_srilanka.pc.png",
            "int_st_barthelemy.pc.png",
            "int_st_vincent.pc.png",
            "int_sudan.pc.png",
            "int_sudan_rugby.pc.png",
            "int_sweden.pc.png",
            "int_switzerland.pc.png",
            "int_tahiti.pc.png",
            "int_tanzania.pc.png",
            "int_thailand.pc.png",
            "int_tonga.pc.png",
            "int_trinidad.pc.png",
            "int_turkey.pc.png",
            "int_turkey_union.pc.png",
            "int_turks_caicos.pc.png",
            "int_tuvali.pc.png",
            "int_uganda.pc.png",
            "int_uraguay.pc.png",
            "int_uraguay_superuru.pc.png",
            "int_usa.pc.png",
            "int_uzbekistan.pc.png",
            "int_venezuela.pc.png",
            "int_wales.pc.png",
            "int_zambia.pc.png",
            "int_zimbawe.pc.png",
            "int_zimbawe_goshawks.pc.png",
            "int_zimbawe_rugby.pc.png",
            "ml_anthemrc.pc.png",
            "ml_chicagohounds.pc.png",
            "ml_dallasjackals.pc.png",
            "ml_houstonsabercats.pc.png",
            "ml_la.pc.png",
            "ml_miamisharks.pc.png",
            "ml_nefreejacks.pc.png",
            "ml_nola_gold.pc.png",
            "ml_oldglory.pc.png",
            "ml_sandiegolegion.pc.png",
            "ml_seattleseawolves.pc.png",
            "ml_utahwarriors.pc.png",
            "pol_bialystok.pc.png",
            "pol_budowlani.pc.png",
            "pol_budownali_lubin.pc.png",
            "pol_buldo_calosc.pc.png",
            "pol_gwiazdki.pc.png",
            "pol_juvenia_krakow.pc.png",
            "pol_lechia.pc.png",
            "pol_ogniwo.pc.png",
            "pol_orkan_sochaczew.pc.png",
            "pol_pogon_siedlce.pc.png",
            "pol_posnania.pc.png",
            "pol_skra.pc.png",
            "por_aac.pc.png",
            "por_agronomia.pc.png",
            "por_belenenses.pc.png",
            "por_benfica.pc.png",
            "por_cascais.pc.png",
            "por_cdul.pc.png",
            "por_cdup.pc.png",
            "por_direito.pc.png",
            "por_lousa.pc.png",
            "por_saomiguel.pc.png",
            "por_top10.pc.png",
            "pro_agen.pc.png",
            "pro_angouleme.pc.png",
            "pro_aviron.pc.png",
            "pro_beziers.pc.png",
            "pro_biarritz.pc.png",
            "pro_bourrg_en_bresse.pc.png",
            "pro_carcassonne.pc.png",
            "pro_colomiers.pc.png",
            "pro_grenoble.pc.png",
            "pro_landes.pc.png",
            "pro_massy.pc.png",
            "pro_montaunban.pc.png",
            "pro_mont_de_marsan.pc.png",
            "pro_narbonne.pc.png",
            "pro_nevers.pc.png",
            "pro_oyonnax.pc.png",
            "pro_provence.pc.png",
            "pro_rouen.pc.png",
            "pro_sa_vx_charente.pc.png",
            "pro_stade_aurillacois.pc.png",
            "pro_stade_nicois.pc.png",
            "pro_valence.pc.png",
            "pro_vannes.pc.png",
            "rep_afghanistan.pc.png",
            "rep_albania.pc.png",
            "rep_algeria.pc.png",
            "rep_andorra.pc.png",
            "rep_angola.pc.png",
            "rep_antigua.pc.png",
            "rep_argentina.pc.png",
            "rep_armenia.pc.png",
            "rep_australia.pc.png",
            "rep_austria.pc.png",
            "rep_azerbaijan.pc.png",
            "rep_bahamas.pc.png",
            "rep_bahrain.pc.png",
            "rep_bangladesh.pc.png",
            "rep_barbados.pc.png",
            "rep_belarus.pc.png",
            "rep_belgium.pc.png",
            "rep_belguim.pc.png",
            "rep_belize.pc.png",
            "rep_benin.pc.png",
            "rep_bhutan.pc.png",
            "rep_bigant.pc.png",
            "rep_bigant_female.pc.png",
            "rep_bigant_male.pc.png",
            "rep_bolivia.pc.png",
            "rep_bosnia.pc.png",
            "rep_botswana.pc.png",
            "rep_brazil.pc.png",
            "rep_brunei.pc.png",
            "rep_bulgaria.pc.png",
            "rep_burkinafaso.pc.png",
            "rep_burundi.pc.png",
            "rep_cambodia.pc.png",
            "rep_cameroon.pc.png",
            "rep_canada.pc.png",
            "rep_capeverde.pc.png",
            "rep_car.pc.png",
            "rep_chad.pc.png",
            "rep_chile.pc.png",
            "rep_china.pc.png",
            "rep_columbia.pc.png",
            "rep_comoros.pc.png",
            "rep_congo.pc.png",
            "rep_cookislands.pc.png",
            "rep_costarica.pc.png",
            "rep_croatia.pc.png",
            "rep_cuba.pc.png",
            "rep_cyprus.pc.png",
            "rep_czechia.pc.png",
            "rep_czechrep.pc.png",
            "rep_denmark.pc.png",
            "rep_djibouti.pc.png",
            "rep_dominica.pc.png",
            "rep_dominican_republic.pc.png",
            "rep_drc.pc.png",
            "rep_east_timor.pc.png",
            "rep_ecuador.pc.png",
            "rep_egypt.pc.png",
            "rep_el_salvador.pc.png",
            "rep_england.pc.png",
            "rep_eq_guinea.pc.png",
            "rep_eritrea.pc.png",
            "rep_estonia.pc.png",
            "rep_eswatini.pc.png",
            "rep_ethiopia.pc.png",
            "rep_fiji.pc.png",
            "rep_finland.pc.png",
            "rep_france.pc.png",
            "rep_gabon.pc.png",
            "rep_gambia.pc.png",
            "rep_georgia.pc.png",
            "rep_germany.pc.png",
            "rep_ghana.pc.png",
            "rep_great_britain.pc.png",
            "rep_greece.pc.png",
            "rep_grenada.pc.png",
            "rep_guatemala.pc.png",
            "rep_guinea.pc.png",
            "rep_guinea_bissau.pc.png",
            "rep_guyana.pc.png",
            "rep_haiti.pc.png",
            "rep_holland.pc.png",
            "rep_honduras.pc.png",
            "rep_hong_kong.pc.png",
            "rep_hungary.pc.png",
            "rep_iceland.pc.png",
            "rep_india.pc.png",
            "rep_indonesia.pc.png",
            "rep_iran.pc.png",
            "rep_iraq.pc.png",
            "rep_ireland.pc.png",
            "rep_israel.pc.png",
            "rep_italy.pc.png",
            "rep_ivorycoast.pc.png",
            "rep_jamaica.pc.png",
            "rep_japan.pc.png",
            "rep_jordan.pc.png",
            "rep_kazakhstan.pc.png",
            "rep_kenya.pc.png",
            "rep_kiribati.pc.png",
            "rep_kosovo.pc.png",
            "rep_kuwait.pc.png",
            "rep_kyrgyzstan.pc.png",
            "rep_laos.pc.png",
            "rep_latvia.pc.png",
            "rep_lebanon.pc.png",
            "rep_lesotho.pc.png",
            "rep_liberia.pc.png",
            "rep_libya.pc.png",
            "rep_liechtenstein.pc.png",
            "rep_lithuania.pc.png",
            "rep_luxembourg.pc.png",
            "rep_macedonia.pc.png",
            "rep_madagascar.pc.png",
            "rep_malawi.pc.png",
            "rep_malaysia.pc.png",
            "rep_maldives.pc.png",
            "rep_mali.pc.png",
            "rep_malta.pc.png",
            "rep_marshall_islands.pc.png",
            "rep_mauritania.pc.png",
            "rep_mauritius.pc.png",
            "rep_mexico.pc.png",
            "rep_micronesia.pc.png",
            "rep_moldova.pc.png",
            "rep_monaco.pc.png",
            "rep_mongolia.pc.png",
            "rep_montenegro.pc.png",
            "rep_morocco.pc.png",
            "rep_mozambique.pc.png",
            "rep_myanmar.pc.png",
            "rep_namibia.pc.png",
            "rep_nauru.pc.png",
            "rep_nepal.pc.png",
            "rep_netherlands.pc.png",
            "rep_new_zealand.pc.png",
            "rep_nicaragua.pc.png",
            "rep_niger.pc.png",
            "rep_nigeria.pc.png",
            "rep_norway.pc.png",
            "rep_nz.pc.png",
            "rep_oman.pc.png",
            "rep_pakistan.pc.png",
            "rep_palau.pc.png",
            "rep_panama.pc.png",
            "rep_paraguay.pc.png",
            "rep_peru.pc.png",
            "rep_philippines.pc.png",
            "rep_png.pc.png",
            "rep_poland.pc.png",
            "rep_portugal.pc.png",
            "rep_qatar.pc.png",
            "rep_romania.pc.png",
            "rep_russia.pc.png",
            "rep_rwanda.pc.png",
            "rep_saintkittsandnevis.pc.png",
            "rep_saintlucia.pc.png",
            "rep_saintvincentandthegrenadines.pc.png",
            "rep_samoa.pc.png",
            "rep_sanmarino.pc.png",
            "rep_saotome.pc.png",
            "rep_saudiarabia.pc.png",
            "rep_scotland.pc.png",
            "rep_senegal.pc.png",
            "rep_serbia.pc.png",
            "rep_seychelles.pc.png",
            "rep_sierra_leone.pc.png",
            "rep_singapore.pc.png",
            "rep_slovakia.pc.png",
            "rep_slovenia.pc.png",
            "rep_solomonislands.pc.png",
            "rep_somalia.pc.png",
            "rep_southafrica.pc.png",
            "rep_southkorea.pc.png",
            "rep_south_africa.pc.png",
            "rep_south_sudan.pc.png",
            "rep_spain.pc.png",
            "rep_srilanka.pc.png",
            "rep_sudan.pc.png",
            "rep_suriname.pc.png",
            "rep_sweden.pc.png",
            "rep_switzerland.pc.png",
            "rep_syria.pc.png",
            "rep_tajikistan.pc.png",
            "rep_tanzania.pc.png",
            "rep_thailand.pc.png",
            "rep_togo.pc.png",
            "rep_tonga.pc.png",
            "rep_trinidad.pc.png",
            "rep_tunisia.pc.png",
            "rep_turkey.pc.png",
            "rep_turkmenistan.pc.png",
            "rep_tuvalu.pc.png",
            "rep_uganda.pc.png",
            "rep_ukraine.pc.png",
            "rep_united_arab_emirates.pc.png",
            "rep_united_states.pc.png",
            "rep_uraguay.pc.png",
            "rep_usa.pc.png",
            "rep_uzbekistan.pc.png",
            "rep_vanuatu.pc.png",
            "rep_venezuela.pc.png",
            "rep_vietnam.pc.png",
            "rep_wales.pc.png",
            "rep_yemen.pc.png",
            "rep_zambia.pc.png",
            "rep_zimbabwe.pc.png",
            "rom_alba_iulia.pc.png",
            "rom_baia_mare.pc.png",
            "rom_barlad.pc.png",
            "rom_bucharest_students.pc.png",
            "rom_constanta.pc.png",
            "rom_dinamo.pc.png",
            "rom_galati.pc.png",
            "rom_grivita.pc.png",
            "rom_gura_humorului.pc.png",
            "rom_iasi.pc.png",
            "rom_navodari.pc.png",
            "rom_rapid.pc.png",
            "rom_stiinta.pc.png",
            "rom_suceava.pc.png",
            "rom_timisoara.pc.png",
            "rom_universitatea_cluj.pc.png",
            "rwanda_hippos.pc.png",
            "rwanda_okapis.pc.png",
            "sr_blues.pc.png",
            "sr_brumbies.pc.png",
            "sr_chiefs.pc.png",
            "sr_crusaders.pc.png",
            "sr_fijian_drua.pc.png",
            "sr_highlanders.pc.png",
            "sr_hurricanes.pc.png",
            "sr_moana.pc.png",
            "sr_rebels.pc.png",
            "sr_reds.pc.png",
            "sr_warratahs.pc.png",
            "sr_western_force.pc.png",
            "top14_bayonne.pc.png",
            "top14_bordeaux_begles.pc.png",
            "top14_brive.pc.png",
            "top14_castres.pc.png",
            "top14_clermont.pc.png",
            "top14_larochelle.pc.png",
            "top14_lyon.pc.png",
            "top14_montpellier.pc.png",
            "top14_pau.pc.png",
            "top14_perpigan.pc.png",
            "top14_racing.pc.png",
            "top14_stade_francais.pc.png",
            "top14_toulon.pc.png",
            "top14_toulous.pc.png",
            "urc_benetton.pc.png",
            "urc_bulls.pc.png",
            "urc_cardiff.pc.png",
            "urc_connacht.pc.png",
            "urc_dragons.pc.png",
            "urc_edinburgh.pc.png",
            "urc_glasgow_warriors.pc.png",
            "urc_leinster.pc.png",
            "urc_lions.pc.png",
            "urc_munster.pc.png",
            "urc_ospreys.pc.png",
            "urc_sale_sharks.pc.png",
            "urc_scarletts.pc.png",
            "urc_sharks.pc.png",
            "urc_sharks2.pc.png",
            "urc_stormers.pc.png",
            "urc_ulster.pc.png",
            "urc_zebre.pc.png"
        };

        public static readonly string[] Positions =
        {
            "1 - Prop Left",
            "2 - Hooker",
            "3 - Prop Right",
            "4 - Lock Left",
            "5 - Lock Right",
            "6 - Blind Flank",
            "7 - Open Flank",
            "8 - Number Eight",
            "9 - Scrum Half",
            "10 - Fly Half",
            "11 - Winger Left",
            "12 - Inside Centre",
            "13 - Outside Centre",
            "14 - Winger Right",
            "15 - Full Back",
            "16 - Sub",
            "17 - Sub",
            "18 - Sub",
            "19 - Sub",
            "20 - Sub",
            "21 - Sub",
            "22 - Sub",
            "23 - Sub"
        };

        public static readonly string[] ShortRoles =
        {
            "FB", // Fullback
            "W", // Rugby League Wing
            "WL", // Winger Left
            "WR", // Winger Right
            "C", // Rugby League Centre
            "IC", // Inside Centre
            "OC", // Outside Centre
            "FE", // Rugby League FiveEight
            "HB", // Rugby League Halfback
            "FH", // Fly Half
            "SH", // Scrum Half
            "FR", // Rugby League Front Row
            "PL", // Prop Left
            "PR", // Prop Right
            "HK", // Hooker
            "SR", // Rugby League Second Row
            "L", // Rugby League Lock
            "LL", // Lock Left
            "LR", // Lock Right
            "FK", // Flank?
            "OF", // Open Flank
            "BF", // Blind Flank
            "N8" // Number Eight
        };

        public static readonly string[] Roles =
        {
            "Fullback",
            "Rugby League Wing",
            "Winger Left",
            "Winger Right",
            "Rugby League Centre",
            "Inside Centre",
            "Outside Centre",
            "Rugby League FiveEight",
            "Rugby League Halfback",
            "Fly Half",
            "Scrum Half",
            "Rugby League Front Row",
            "Prop Left",
            "Prop Right",
            "Hooker",
            "Rugby League Second Row",
            "Rugby League Lock",
            "Lock Left",
            "Lock Right",
            "Flank?",
            "Open Flank",
            "Blind Flank",
            "Number Eight"
        };

        public static readonly string[] UnionRoles =
        {
            "Fullback",
            "Winger Left",
            "Winger Right",
            "Inside Centre",
            "Outside Centre",
            "Fly Half",
            "Scrum Half",
            "Prop Left",
            "Prop Right",
            "Hooker",
            "Lock Left",
            "Lock Right",
            "Open Flank",
            "Blind Flank",
            "Number Eight"
        };

        public static readonly string[] Chirality =
        {
            "Left",
            "Right"
        };

        public static readonly string[] ConversionStyle = 
        {
            "Generic",
            "Richie Mounga",
            "Jordie Barret",
            "Damian Mckenzie",
            "Romain Ntamack",
            "Owen Farrell",
            "Dan Biggar",
            "Leigh Halfpenny",
            "Nicolas Sanchez",
            "Thomas Ramos",
            "Handre Pollard",
            "George Ford",
            "Johnny Sexton",
            "Beauden Barrett"
        };
    }
}
